version: '3.8'

services:
  test-runner:
    build:
      context: .
      target: builder
    working_dir: /app
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=airline_user
      - DB_PASSWORD=airline_pass
      - DB_NAME=airline_booking_test
      - ES_ADDRESSES=http://elasticsearch:9200
      - APP_ENV=test
      - LOG_LEVEL=error
    depends_on:
      - mysql-test
      - elasticsearch-test
    networks:
      - test-network

  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: airline_booking_test
      MYSQL_USER: airline_user
      MYSQL_PASSWORD: airline_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql-test-data:/var/lib/mysql
    networks:
      - test-network

  elasticsearch-test:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9201:9200"
    volumes:
      - es-test-data:/usr/share/elasticsearch/data
    networks:
      - test-network

volumes:
  mysql-test-data:
  es-test-data:

networks:
  test-network:
    driver: bridge
